### ISSUE TITLE
WAITING: cms-builder doesn't always run composer install

### ISSUE THREAD

**Issue by seqbat** [tes/cms-builder#20]
@andriokha commented on [Tue Jun 13 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296)

@embob has been having this problem for a long time.

Investigate and code review that part of cms-builder, possibly add diagnostics if necessary.

**Results**
It looks like this might've been caused by `cms-builder build` being run outside of the project root.

1. I've asked @embob if she can try from the project root for a bit to verify
1. I've added an issue for making cms-builder more developer-friendly: #304
1. I've updated the cms-vision docs to be clearer about where it can be run: https://github.com/tes/cms-supply-distribution-platform/pull/305

I've put WAITING in the title and will wait a week before closing to give time for @embob to confirm the fix.

---

@dawehner commented on [Tue Jun 13 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296#issuecomment-308092416)

As far as I understand the code responsible for it is```\tes\CmsBuilder\Command\Platform\BuildCommand::execute```

In there the magic is all happening with the call to the platform build tool: 
``` 
           'platform',
            'build',
            // Ensure that composer build runs every time.
            '--no-archive',
            '--source=.',
            '--destination=_www'
```

Let's see what platform is doing.

---

@dawehner commented on [Tue Jun 13 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296#issuecomment-308094052)

In https://github.com/platformsh/platformsh-cli/blob/1a7d66ae5d2ff86a8eef67e0a4a1b145349e8e81/src/Local/LocalBuild.php#L266 there is some magic, but giving we have no-archive, this should be skipped.

In https://github.com/platformsh/platformsh-cli/blob/1a7d66ae5d2ff86a8eef67e0a4a1b145349e8e81/src/Local/LocalBuild.php#L307 then we probably call out to the ```$buildFlavor``` and deal with things there.

@andriokha Do you have idea whether https://github.com/platformsh/platformsh-cli/blob/development/src/Local/BuildFlavor/Composer.php or https://github.com/platformsh/platformsh-cli/blob/development/src/Local/BuildFlavor/Drupal.php is used?

---

@andriokha commented on [Tue Jun 13 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296#issuecomment-308114279)

@dawehner no, I've not come across either of them I'm afraid.

---

@andriokha commented on [Tue Jun 13 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296#issuecomment-308116007)

fwiw @embob was on Platform CLI 3.16.2 and has now updated to 3.17.

---

@andriokha commented on [Wed Jun 14 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296#issuecomment-308391190)

It looks like this might've been caused by `cms-builder build` being run outside of the project root.

1. I've asked @embob if she can try from the project root for a bit to verify
1. I've added an issue for making cms-builder more developer-friendly: #304
1. I've updated the cms-vision docs to be clearer about where it can be run: https://github.com/tes/cms-supply-distribution-platform/pull/305

---

@andriokha commented on [Tue Jun 20 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296#issuecomment-309704292)

> The configuration synchronization failed validation.
> Configuration _devel.settings_ depends on the _Devel_ module that will not be installed after import.
> Configuration _devel.toolbar.settings_ depends on the _Devel_ module that will not be installed after import.

It looks like it's caused by left-over devel settings files when devel's not configured to be enabled in core.extension.yml.

---

@dawehner commented on [Tue Jun 20 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296#issuecomment-309715337)

> It looks like it's caused by left-over devel settings files when devel's not configured to be enabled in core.extension.yml.

Interesting. Does that mean config merge should do some additional filtering?

---

@andriokha commented on [Tue Jun 20 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296#issuecomment-309719235)

@dawehner er weird, I think there's a deleted comment here. @embob had that problem earlier, I think it's a red herring though (eg. it can happen if you ensure devel's not in your core.extension.yml but don't notice those untracked devel files, do a rebuild and bang). Far from certain tho.

---

@andriokha commented on [Tue Jun 27 2017](https://github.com/tes/cms-supply-distribution-platform/issues/296#issuecomment-311294444)

@embob assigning this to you: if there haven't been any further problems feel free to close.

**Comment by andriokha** [comment]
Closing, doesn't seem to be a problem anymore.
