### ISSUE TITLE
Drush commands with too many arguments

### ISSUE THREAD

**Issue by scotthooker** [tes/cms-builder#6]
`smp:cms-vision Scott$ cms-builder drush dis panels

                                                           
  [Symfony\Component\Console\Exception\RuntimeException]   
  Too many arguments, expected arguments "command" "cmd".  
                                                           

drush [<cmd>]

smp:cms-vision Scott$ 
`

For example - doesn't like that or things like me flagging it with -y

**Comment by alexpott** [comment]
This is fixed by https://github.com/mglaman/platform-docker/pull/82

In cms-builder already to use you can do:
```bash
cms-builder drush dis panels --drush-option=-y
```
